FROM node:8.0
ENV HOME=/usr/src/app

RUN mkdir $HOME
#RUN chown -R node:root /usr/src/
#RUN chmod -R 666 /usr/src/
WORKDIR $HOME

ENV http_proxy=http://proxy.int.8451.com:80
ENV https_proxy=http://proxy.int.8451.com:443
ENV no_proxy=*.8451.com

COPY main.js $HOME/main.js
COPY package.json $HOME/package.json

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update && apt-get install yarn

RUN yes | apt-get install zip

RUN yarn install

RUN yarn global add @angular/cli
RUN yarn global add @nrwl/schematics

RUN ng set --global packageManager=yarn

EXPOSE 3000
EXPOSE 49153

CMD node main.js
